{"componentChunkName":"component---src-templates-series-jsx","path":"/series/javascript/","result":{"data":{"posts":{"nodes":[{"excerpt":"자바스크립트에서 에러가 발생하면 스크립트는 죽고, 콘솔에 에러가 출력된다. 그러나 문을 사용하면 스크립트가 죽는 걸 방지하고, 에러를 잡아서(catch) 예외 처리를 할 수 있게 된다. try...catch문 try...catch문의 동작은 다음과 같다. 먼저,  안의 코드가 실행된다. 에러가 없다면,  안의 마지막 줄까지 실행되고,  블록은 건너뛴다. …","fields":{"slug":"/error-handling/"},"frontmatter":{"date":"March 07, 2024","update":"Mar 07, 2024","title":"⚠️ 자바스크립트의 예외 처리","tags":["javascript","try~catch","async","await"]}},{"excerpt":"알고리즘을 풀면서 아래와 같은 함수를 작성하여, 값을 변경하고 두 수의 위치를 바꾸려고 했다. 하지만 의도와는 다르게 은 위치를 바꾸지 못하고 는 원본 그대로를 출력한다. 왜 함수 n1, n2의 값을 변경하지 못하는 걸까? 🥲 자바스크립트에서 기본 타입(primitive types)은 으로 함수에 전달되기 때문이다. 이는 함수에 값을 전달할 때, 실제 값…","fields":{"slug":"/js-type/"},"frontmatter":{"date":"March 21, 2024","update":"Mar 21, 2024","title":"🙌 값에 의한 전달(Pass by Value)와 참조에 의한 전달(Pass by Reference) ","tags":["javascript","pass by value","pass by reference"]}}]}},"pageContext":{"series":"javascript"}},"staticQueryHashes":[],"slicesMap":{}}