{"componentChunkName":"component---src-templates-series-jsx","path":"/series/javascript/","result":{"data":{"posts":{"nodes":[{"excerpt":"자바스크립트에서 에러가 발생하면 스크립트는 죽고, 콘솔에 에러가 출력된다. 그러나 문을 사용하면 스크립트가 죽는 걸 방지하고, 에러를 잡아서(catch) 예외 처리를 할 수 있게 된다. try...catch문 try...catch문의 동작은 다음과 같다. 먼저,  안의 코드가 실행된다. 에러가 없다면,  안의 마지막 줄까지 실행되고,  블록은 건너뛴다. …","fields":{"slug":"/error-handling/"},"frontmatter":{"date":"March 07, 2024","update":"Mar 07, 2024","title":"⚠️ 자바스크립트의 예외 처리","tags":["javascript","try~catch","async","await"]}}]}},"pageContext":{"series":"javascript"}},"staticQueryHashes":[],"slicesMap":{}}